# Generated by Django 2.2.7 on 2019-11-25 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('introduce', models.TextField()),
                ('age', models.CharField(max_length=5)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('public_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
