# Generated by Django 2.2.7 on 2019-11-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='public_date',
            new_name='published_date',
        ),
    ]
